name: form_validatorchi
description: This is a simple form validator for best developers in the world
version: 1.0.0
repository: https://github.com/AkmaljonAbdirakhimov/form_validators
homepage: https://github.com/AkmaljonAbdirakhimov/form_validators

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

license: MIT